import Head from "next/head";
import { FaFacebookF, FaLinkedinIn, FaGoogle, FaRegEnvelope } from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
          <div className="w-3/5 p-4">
            <p className="text-green-600 font-bold text-start">
              Company<span className="text-black">Name</span>
            </p>
            <h2 className="text-2xl mb-2 font-bold text-green-600 my-8">Sign in to Account</h2>
            <div className="border-2 w-10  border-green-600 inline-block mb-2"></div>
            <div className="flex justify-center my-2 gap-2">
              <a href="#" className="border-2 border-gray-200 p-2 rounded-full">
                <FaFacebookF className="text-sm" />
              </a>
              <a href="#" className="border-2 border-gray-200 p-2 rounded-full">
                <FaGoogle className="text-sm" />
              </a>
              <a href="#" className="border-2 border-gray-200 p-2 rounded-full">
                <FaLinkedinIn className="text-sm" />
              </a>
            </div>
            <p className="text-sm mb-2 text-gray-400 my-4">or use your email account</p>
            <div className="flex flex-col items-center">
              <div className="bg-gray-100 w-64 p-3 flex gap-2 align-center mb-4">
                <FaRegEnvelope className="text-gray-400 text-xl" />
                <input type="email" className="bg-gray-100 text-sm outline-none text-gray-500" placeholder="Email" />
              </div>
              <div className="bg-gray-100 w-64 p-3 flex gap-2 align-center">
                <MdLockOutline className="text-gray-400 text-xl" />
                <input
                  type="password"
                  className="bg-gray-100 text-sm outline-none text-gray-500"
                  placeholder="Password"
                />
              </div>
              <div className="flex justify-between w-64 my-2">
                <label className="text-xs">
                  <input type="checkbox" className="text-sm" placeholder="Password" /> Remember me
                </label>
                <a href="#" className="text-xs">
                  Forgot Password?
                </a>
              </div>
              <a
                href="#"
                className="border-2 border-green-600 text-green-600 rounded-full px-10 py-1.5 inline-block mt-2 transition-all hover:bg-green-600 hover:text-white"
              >
                Sign Up
              </a>
            </div>
          </div>
          <div className="w-2/5 p-5 bg-green-600 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12">
            <h2 className="text-2xl mb-2 font-bold">Hello, Friend!</h2>
            <div className="border-2 w-10  border-white inline-block mb-2"></div>
            <p className="text-sm mb-2">Fill up personal information and start journey with us</p>
            <a
              href="#"
              className="border-2 border-white rounded-full px-10 py-1.5 inline-block mt-2 transition-all hover:bg-white hover:text-green-600"
            >
              Sign Up
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
